### ISSUE TITLE
Verify NodeJS version compatability with Foundry v12

### ISSUE THREAD

**Issue by damien** [Sparky939/godbound#1]
# Problem

This project may be using a version of NodeJS not used by Foundry. We should verify that this project is configured to use a version of NodeJS compatible with the current version of Foundry: NodeJS 18.x, NodeJS 20.x, or NodeJS 22.x+.

# Context

From https://foundryvtt.com/article/installation/
> Note that a relatively modern version of Node.js is required in order to support various security features which are required by the application. Please use Node.js version 18.x+ (20.x is recommended, 21.x incompatible).

I'm not sure what _exactly_ could break here or how far along the Foundry dev team are to using a more recent version of node; this will likely be determined by whatever version of Electron they're using.

**Comment by Sparky939** [comment]
I've bumped our core version from v11 compatibility to v12, upgraded node dependencies and run a test build. This all looks fine so I'm closing this for now
